from django.urls import path
from . import views

urlpatterns = [
    path('', views.inventory_view, name='inventory'),
    path('inventory/', views.inventory_view), # Alias for reliability
    path('all-inventory-items/', views.all_inventory_items_view, name='all_inventory_items'),
    path('inventory-logs/', views.inventory_logs_view, name='inventory_logs'),
    path('products/', views.products_view, name='products'),
    path('purchase-request/index', views.purchase_order_requests_view, name='purchase_order_requests'),
    path('purchase-orders/', views.purchase_orders_view, name='purchase_orders'),
    path('inventory/archive/<int:item_id>/', views.toggle_archive, name='toggle_archive'),
    path('inventory/bulk-archive/', views.bulk_archive, name='bulk_archive'),
    path('inventory/update-stock/', views.update_stock, name='update_stock'),
    path('inventory/logs/<int:item_id>/', views.get_inventory_logs, name='get_inventory_logs'),
    path('inventory/update/<int:item_id>/', views.update_item, name='update_item'),
    path('products/create/', views.create_product, name='create_product'),
    path('products/create-combo/', views.create_combo_product, name='create_combo_product'),
    path('products/delete/<int:product_id>/', views.toggle_product_archive, name='delete_product'),
    path('products/duplicate/<int:product_id>/', views.duplicate_product, name='duplicate_product'),
    path('products/<int:product_id>/', views.product_detail, name='product_detail'),
    path('products/<int:product_id>/update/', views.update_product, name='update_product'),
    path('products/<int:product_id>/image/update/', views.update_product_image, name='update_product_image'),
    path('products/<int:product_id>/image/delete/', views.delete_product_image, name='delete_product_image'),
    path('products/<int:product_id>/materials/add/', views.add_product_material, name='add_product_material'),
    path('purchase-orders/<int:po_id>/', views.purchase_order_detail, name='purchase_order_detail'),
    path('purchase-order/create', views.create_po, name='create_po'),
    path('purchase-order/<int:po_id>/add-item', views.add_item_to_po, name='add_item_to_po'),
    path('purchase-order/<int:po_id>/archive', views.toggle_po_archive, name='toggle_po_archive'),
    path('purchase-order/<int:po_id>/delete', views.delete_po, name='delete_po'),
    path('purchase-order/<int:po_id>/update', views.update_po, name='update_po'),
    path('purchase-order/<int:po_id>/toggle-lock', views.toggle_po_lock, name='toggle_po_lock'),
    path('purchase-order/item/<int:item_id>/delete', views.delete_po_item, name='delete_po_item'),
    path('purchase-order/item/<int:item_id>/update', views.update_po_item, name='update_po_item'),
    path('purchase-order-request/create', views.create_purchase_order_request, name='create_pr'),
    path('purchase-order-request/update/<int:pr_id>', views.update_purchase_order_request, name='update_pr'),
    path('purchase-order-request/delete/<int:pr_id>', views.delete_purchase_order_request, name='delete_pr'),
    path('purchase-order-request/cancel/<int:pr_id>', views.cancel_purchase_order_request, name='cancel_pr'),
    path('purchase-order-request/add-to-po', views.add_requests_to_po, name='add_to_po'),
    path('api/purchase-order/<int:po_id>/items', views.get_po_items_api, name='get_po_items_api'),

    # Dashboard
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('api/dashboard/stats/', views.api_dashboard_stats, name='api_dashboard_stats'),
    path('api/activity/', views.api_activity_log, name='api_activity_log'),

    # Employment
    path('employees/', views.employee_list_view, name='employee_list'),
    path('employees/create/', views.create_employee, name='create_employee'),
    path('employees/<int:emp_id>/', views.employee_detail_view, name='employee_detail'),
    path('employees/<int:emp_id>/update/', views.update_employee, name='update_employee'),
    path('employees/<int:emp_id>/delete/', views.delete_employee, name='delete_employee'),
    path('employees/<int:emp_id>/unarchive/', views.unarchive_employee, name='unarchive_employee'),
    path('employees/<int:emp_id>/hard-delete/', views.hard_delete_employee, name='hard_delete_employee'),
    path('employees/<int:emp_id>/upload-doc/', views.upload_employee_document, name='upload_employee_document'),
    path('employees/<int:emp_id>/doc/<int:doc_id>/download/', views.download_employee_document, name='download_employee_document'),
    path('employees/<int:emp_id>/doc/<int:doc_id>/view/', views.view_employee_document, name='view_employee_document'),
    path('employees/<int:emp_id>/doc/<int:doc_id>/delete/', views.delete_employee_document, name='delete_employee_document'),
    path('employees/<int:emp_id>/export-pdf/', views.export_employee_pdf, name='export_employee_pdf'),

    # Education/Skills
    path('employees/<int:emp_id>/education/add/', views.add_employee_education, name='add_employee_education'),
    path('employees/<int:emp_id>/education/delete/<int:edu_id>/', views.delete_employee_education, name='delete_employee_education'),
    path('employees/<int:emp_id>/skill/add/', views.add_employee_skill, name='add_employee_skill'),
    path('employees/<int:emp_id>/skill/delete/<int:skill_id>/', views.delete_employee_skill, name='delete_employee_skill'),

    # Employment History
    path('employees/<int:emp_id>/employment-history/add/', views.add_employee_employment_history, name='add_employee_employment_history'),
    path('employees/<int:emp_id>/employment-history/delete/<int:history_id>/', views.delete_employee_employment_history, name='delete_employee_employment_history'),

    # Reports
    path('reports/', views.reports_view, name='reports'),
    path('reports/collections/', views.collections_report_view, name='report_collections'),
    path('reports/expenses/', views.expenses_report_view, name='report_expenses'),
    path('reports/monthly/', views.monthly_report_view, name='report_monthly'),

    # Operations
    path('clients/', views.clients_view, name='clients'),
    path('job-orders/', views.job_orders_view, name='job_orders'),
    path('job-orders/create/', views.create_job_order, name='create_job_order'),
    path('job-orders/<int:jo_id>/', views.job_order_detail_view, name='job_order_detail'),
    path('job-orders/<int:jo_id>/add-product/', views.add_jo_product, name='add_jo_product'),
    path('job-order-products/', views.jo_products_view, name='jo_products'),
    path('payments/', views.payments_view, name='payments'),
    path('job-order-products/releasing/', views.jo_releasing_view, name='jo_releasing'),
    path('labor-output/', views.labor_output_view, name='labor_output'),
    path('labor-output/add/', views.add_labor_ajax, name='add_labor_ajax'),
    path('labor-output/approve/<int:labor_id>/', views.approve_labor_view, name='approve_labor'),
    path('labor-output/jo-products/<int:jo_id>/', views.get_jo_products, name='get_jo_products'),
    path('labor-output/delete/<int:labor_id>/', views.delete_labor_ajax, name='delete_labor_ajax'),
    path('withdrawal-slips/', views.withdrawal_slips_view, name='withdrawal_slips'),
    path('dr/', views.dr_view, name='dr'),
    path('dr/create/', views.api_create_dr, name='api_create_dr'),
    path('dr/<int:dr_id>/', views.dr_detail_view, name='dr_detail'),
    path('dr/<int:dr_id>/add-item/', views.api_add_dr_item, name='api_add_dr_item'),
    path('dr/<int:dr_id>/lock/', views.api_lock_dr, name='api_lock_dr'),
    path('dr/item/<int:item_id>/delete/', views.api_delete_dr_item, name='api_delete_dr_item'),
    path('expenses/', views.expenses_view, name='expenses'),
    path('expenses-summary/', views.expenses_summary_view, name='expenses_summary'),
    path('expenses-category/', views.expenses_category_view, name='expenses_category'),
    path('api/expense-category/update/<int:category_id>/', views.api_update_expense_category, name='api_update_expense_category'),
    path('api/expense-category/delete/<int:category_id>/', views.api_delete_expense_category, name='api_delete_expense_category'),
    path('expenses-category-types/', views.expenses_types_view, name='expenses_types'),
    path('api/expense-type/update/<int:type_id>/', views.api_update_expense_type, name='api_update_expense_type'),
    path('api/expense-type/delete/<int:type_id>/', views.api_delete_expense_type, name='api_delete_expense_type'),
    path('suppliers/', views.suppliers_view, name='suppliers'),
    path('api/supplier/update/<int:supplier_id>/', views.api_update_supplier, name='api_update_supplier'),
    path('api/supplier/delete/<int:supplier_id>/', views.api_delete_supplier, name='api_delete_supplier'),
    path('api/expense/update/<int:expense_id>/', views.api_update_expense, name='api_update_expense'),
    path('api/expense/delete/<int:expense_id>/', views.api_delete_expense, name='api_delete_expense'),
    path('api/expenses-summary/update/<int:summary_id>/', views.api_update_expense_summary, name='api_update_expense_summary'),
    path('api/expenses-summary/delete/<int:summary_id>/', views.api_delete_expense_summary, name='api_delete_expense_summary'),
    path('production-area/<int:area_id>/', views.area_view, name='area_view'),
    path('production/acknowledge/<int:product_id>/', views.acknowledge_product, name='acknowledge_product'),
    path('production/transfer/<int:product_id>/', views.transfer_product, name='transfer_product'),
    path('production/force-sync/', views.force_sync_production, name='force_sync_production'),
    path('job-order-products/cgs', views.cgs_view, name='jo_products_cgs'),
    path('employees-salary/index', views.employee_salary_view, name='employee_salary'),
    path('employees-payroll/index', views.payroll_view, name='payroll'),
    path('employees-payroll/<int:payroll_id>/', views.payroll_detail_view, name='payroll_detail'),
    path('api/payroll-record/update/', views.update_payroll_record, name='update_payroll_record'),
    path('api/client/update/<int:client_id>/', views.update_client, name='update_client'),
    path('api/job-order/update/<int:jo_id>/', views.update_job_order, name='update_job_order'),
    path('api/job-order/<int:jo_id>/add-payment/', views.api_add_payment, name='add_payment'),
    path('api/job-order/<int:jo_id>/update-discount/', views.api_update_discount, name='update_discount'),
    path('api/product-details/<int:product_id>/', views.api_get_product_details, name='api_get_product_details'),
    path('production/send-to-production/<int:product_id>/', views.send_to_production, name='send_to_production'),
    path('api/generate-withdrawal-slip/<int:jo_id>/', views.api_generate_withdrawal_slip, name='generate_withdrawal_slip'),
    path('api/withdrawal-slip-details/<int:product_id>/', views.api_get_withdrawal_slip_details, name='get_withdrawal_slip_details'),
    path('withdrawal-slip/<int:slip_id>/', views.withdrawal_slip_detail_view, name='withdrawal_slip_detail'),
    path('withdrawal-slip/<int:slip_id>/print/', views.print_withdrawal_slip, name='print_withdrawal_slip'),
    path('api/withdrawal-slip/create/', views.create_withdrawal_slip_ajax, name='create_withdrawal_slip_ajax'),
    path('api/withdrawal-slip/<int:slip_id>/add-item/', views.add_withdrawal_slip_item_ajax, name='add_withdrawal_slip_item_ajax'),
    path('api/withdrawal-slip-item/<int:item_id>/release/', views.release_withdrawal_slip_item_ajax, name='release_withdrawal_slip_item_ajax'),
    path('api/withdrawal-slip-item/<int:item_id>/delete/', views.delete_withdrawal_slip_item_ajax, name='delete_withdrawal_slip_item_ajax'),
    path('api/withdrawal-slip/<int:slip_id>/complete/', views.complete_withdrawal_slip_ajax, name='complete_withdrawal_slip_ajax'),
    path('api/job-order/update-material/<int:jopm_id>/', views.api_update_jo_product_materials, name='update_jo_product_material'),
    path('api/job-order/archive/<int:jo_id>/', views.toggle_job_order_archive, name='toggle_job_order_archive'),
    path('api/job-order/<int:jo_id>/void/', views.api_void_job_order, name='void_job_order'),
    path('api/job-order-product/<int:product_id>/pack/', views.api_pack_jo_product, name='api_pack_jo_product'),
    path('api/job-order-product/<int:product_id>/release/', views.api_release_jo_product, name='api_release_jo_product'),
    path('api/job-order-product/<int:product_id>/details/', views.get_jo_product_release_details, name='api_jo_product_details'),
    path('api/client/archive/<int:client_id>/', views.archive_client, name='archive_client'),
    path('api/client/restore/<int:client_id>/', views.restore_client, name='restore_client'),
    path('inventory/bulk-archive-clients/', views.bulk_archive_clients, name='bulk_archive_clients'),
    path('clients/<int:client_id>/', views.client_detail_view, name='client_detail'),
    path('api/payment/update/<int:payment_id>/', views.api_update_payment, name='api_update_payment'),
    path('job-order/<int:jo_id>/print/', views.print_job_order, name='print_job_order'),

    # User Management & RBAC
    path('user/index', views.user_index_view, name='user_index'),
    path('user/matrix', views.user_matrix_view, name='user_matrix'),
    path('auth-assignment/index', views.auth_assignment_view, name='auth_assignment'),
    path('auth-item/index', views.auth_item_view, name='auth_item'),
    
    # User Management APIs
    path('api/user/toggle-status/', views.api_toggle_user_status, name='api_toggle_user_status'),
    path('api/user/update/', views.api_update_user, name='api_update_user'),
    path('api/user/toggle-permission/', views.api_toggle_auth_item, name='api_toggle_auth_item'),
    path('api/user/link-employee/', views.api_link_user_employee, name='api_link_user_employee'),
    path('api/auth-item/delete/', views.api_delete_auth_item, name='api_delete_auth_item'),
]
