# Generated by Django 6.0.2 on 2026-02-23 05:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('image', models.TextField(blank=True, default='')),
                ('name', models.CharField(max_length=200)),
                ('sub_unit', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('datetime_updated', models.CharField(blank=True, default='', max_length=50)),
                ('last_inventory', models.CharField(blank=True, default='', max_length=50)),
                ('total_purchases', models.CharField(blank=True, default='', max_length=50)),
                ('total_withdrawal', models.CharField(blank=True, default='', max_length=50)),
                ('total_balance', models.CharField(blank=True, default='', max_length=50)),
                ('price', models.CharField(blank=True, default='', max_length=50)),
                ('inventory_value', models.CharField(blank=True, default='', max_length=50)),
                ('is_negative', models.CharField(default='no', max_length=10)),
                ('color', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('shape', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.CharField(blank=True, default='', max_length=100)),
                ('dimensions', models.CharField(blank=True, default='', max_length=100)),
                ('volume', models.CharField(blank=True, default='', max_length=100)),
                ('material', models.CharField(blank=True, default='', max_length=100)),
                ('addon', models.CharField(blank=True, default='', max_length=200)),
                ('other', models.CharField(blank=True, default='', max_length=200)),
                ('occasion', models.CharField(blank=True, default='', max_length=200)),
                ('is_archived', models.BooleanField(default=False)),
                ('cost', models.CharField(blank=True, default='', max_length=50)),
                ('shipping_fee', models.CharField(blank=True, default='', max_length=50)),
                ('updated_by', models.CharField(default='admin', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.FloatField(default=1.0)),
                ('unit', models.CharField(default='set', max_length=50)),
                ('srp', models.FloatField(default=0.0)),
                ('mp', models.FloatField(default=0.0)),
                ('lp', models.FloatField(default=0.0)),
                ('markup', models.FloatField(default=0.0)),
                ('overhead', models.FloatField(default=0.0)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('is_combo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='Stephen', max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Locked', max_length=50)),
                ('po_number', models.CharField(max_length=100)),
                ('supplier', models.CharField(blank=True, default='', max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('comments', models.TextField(blank=True, default='')),
                ('total', models.FloatField(default=0)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(default='Stephen', max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(default='-', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('quantity', models.FloatField(default=0)),
                ('unit', models.CharField(default='pc', max_length=50)),
                ('status', models.CharField(default='created', max_length=50)),
                ('purchase_order_id', models.CharField(blank=True, default='', max_length=100)),
                ('supplier', models.CharField(blank=True, default='', max_length=200)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(default='Stephen', max_length=100)),
                ('datetime_added', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='Stephen', max_length=100)),
                ('transaction_type', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProductComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, default='', max_length=200)),
                ('quantity', models.FloatField(default=1.0)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_combo_items', to='inventory.inventoryitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('item_name', models.CharField(blank=True, default='', max_length=200)),
                ('quantity', models.FloatField(default=1.0)),
                ('cost', models.FloatField(default=0.0)),
                ('total_cost', models.FloatField(default=0.0)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_materials', to='inventory.inventoryitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.FloatField(default=1)),
                ('unit', models.CharField(default='pc', max_length=50)),
                ('unit_price', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('remarks', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_items', to='inventory.inventoryitem')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder')),
            ],
        ),
    ]
