# Generated by Django 4.2.28 on 2026-02-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_id_alter_inventorylog_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='inventory_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='shipping_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='total_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='total_purchases',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='total_withdrawal',
            field=models.FloatField(default=0.0),
        ),
    ]
