# Generated by Django 4.2.28 on 2026-03-06 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomboitem',
            name='linked_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_combo_items', to='inventory.product'),
        ),
    ]
