# Generated by Django 4.2.28 on 2026-03-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_activitylog_employee_employmenthistory_employeeskill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
