# Generated by Django 4.2.28 on 2026-03-11 08:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_employee_contract_renewal_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('business_name', models.CharField(blank=True, default='', max_length=200)),
                ('mobile_number', models.CharField(blank=True, default='', max_length=50)),
                ('email_address', models.EmailField(blank=True, default='', max_length=200)),
                ('tin', models.CharField(blank=True, default='', max_length=50)),
                ('total_balance', models.FloatField(default=0.0)),
                ('date_enrolled', models.DateTimeField(default=django.utils.timezone.now)),
                ('enrolled_by', models.CharField(default='Stephen', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dv_number', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('particular', models.TextField()),
                ('expense_type', models.CharField(max_length=100)),
                ('fund_source', models.CharField(default='Cash', max_length=100)),
                ('amount', models.FloatField(default=0.0)),
                ('receipt_number', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(default='Stephen', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('quantity', models.FloatField(default=0)),
                ('wip', models.CharField(blank=True, default='', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('order_type', models.CharField(default='Events', max_length=100)),
                ('amount_due', models.FloatField(default=0.0)),
                ('amount_paid', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('product_release_status', models.CharField(default='Pending', max_length=50)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(default='Stephen', max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_orders', to='inventory.client')),
            ],
        ),
    ]
