# Generated by Django 4.2.28 on 2026-03-11 08:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_client_expense_joborder'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('pid', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('product_type', models.CharField(blank=True, default='', max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.FloatField(default=0)),
                ('unit_price', models.FloatField(default=0.0)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('is_packed', models.BooleanField(default=False)),
                ('is_released', models.BooleanField(default=False)),
                ('qty_released', models.FloatField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(default='Stephen', max_length=100)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.joborder')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_type', models.CharField(default='OR', max_length=100)),
                ('or_number', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.FloatField(default=0.0)),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_by', models.CharField(default='Stephen', max_length=100)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='Stephen', max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.client')),
                ('job_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.joborder')),
            ],
        ),
        migrations.CreateModel(
            name='LaborOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_accomplished', models.DateField(default=django.utils.timezone.now)),
                ('particulars', models.TextField(blank=True, default='')),
                ('total_labor_approved', models.FloatField(default=0.0)),
                ('output_type', models.CharField(max_length=100)),
                ('quantity', models.FloatField(default=0)),
                ('unit_price', models.FloatField(default=0.0)),
                ('quantity_approved', models.FloatField(default=0)),
                ('total', models.FloatField(default=0.0)),
                ('datetime_approved', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_outputs', to='inventory.employee')),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_outputs', to='inventory.joborder')),
                ('job_order_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_outputs', to='inventory.joborderproduct')),
            ],
        ),
    ]
