# Generated by Django 4.2.28 on 2026-03-11 09:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_joborderproduct_payment_laboroutput'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='joborderproduct',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joborderproduct',
            name='acknowledged_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='joborderproduct',
            name='is_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joborderproduct',
            name='last_transfer_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='joborderproduct',
            name='current_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.productionarea'),
        ),
    ]
