# Generated by Django 4.2.28 on 2026-03-11 09:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_productionarea_joborderproduct_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wip', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(default='Stephen', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(blank=True, default='', max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Open', max_length=100)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag_delivered_by', models.CharField(blank=True, default='', max_length=100)),
                ('comments', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_receipts', to='inventory.purchaseorder')),
            ],
        ),
    ]
