# Generated by Django 4.2.28 on 2026-03-11 11:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_expensecategory_expensesummary_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='Draft', max_length=50)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(default='Stephen', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='joborderproduct',
            name='labor_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='joborderproduct',
            name='markup_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='joborderproduct',
            name='materials_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='joborderproduct',
            name='overhead_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_rate', models.FloatField(default=0.0)),
                ('total_labor', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField(default=0.0)),
                ('status', models.CharField(default='Draft', max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='inventory.employee')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='inventory.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='Stephen', max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='inventory.employee')),
            ],
            options={
                'verbose_name_plural': 'Employee Salaries',
            },
        ),
    ]
