# Generated by Django 4.2.28 on 2026-03-12 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_payroll_joborderproduct_labor_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborderproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_products', to='inventory.product'),
        ),
    ]
