# Generated by Django 4.2.28 on 2026-03-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_joborderproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
