# Generated by Django 4.2.28 on 2026-03-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_client_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='delivery_mode',
            field=models.CharField(blank=True, default='PICK-UP', max_length=100),
        ),
    ]
