# Generated by Django 4.2.28 on 2026-03-12 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_joborder_delivery_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='transaction_mode',
            field=models.CharField(blank=True, default='Walk-in', max_length=100),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
