# Generated by Django 4.2.28 on 2026-03-12 02:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_joborder_transaction_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborderproduct',
            name='withdrawal_slip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jo_products', to='inventory.withdrawalslip'),
        ),
        migrations.CreateModel(
            name='WithdrawalSlipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.FloatField(default=0)),
                ('withdrawal_slip_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('withdrawal_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.withdrawalslip')),
            ],
        ),
    ]
