# Generated by Django 4.2.28 on 2026-03-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_joborderproduct_withdrawal_slip_withdrawalslipitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('archived', 'Archived'), ('restored', 'Restored'), ('uploaded', 'Uploaded'), ('exported', 'Exported'), ('login', 'Login'), ('status_change', 'Status Change'), ('acknowledged', 'Acknowledged'), ('transferred', 'Transferred'), ('generated', 'Generated'), ('sent_to_production', 'Sent to Production')], max_length=50),
        ),
    ]
