# Generated by Django 4.2.28 on 2026-03-12 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrderProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('item_name', models.CharField(blank=True, default='', max_length=200)),
                ('quantity', models.FloatField(default=1.0)),
                ('cost', models.FloatField(default=0.0)),
                ('total_cost', models.FloatField(default=0.0)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jop_materials', to='inventory.inventoryitem')),
                ('job_order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jop_materials', to='inventory.joborderproduct')),
            ],
        ),
    ]
