# Generated by Django 4.2.28 on 2026-03-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_joborderproductmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
