# Generated by Django 4.2.28 on 2026-03-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_client_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
