# Generated by Django 4.2.28 on 2026-03-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_joborder_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ewt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=50),
        ),
    ]
