# Generated by Django 4.2.28 on 2026-03-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_payment_ewt_alter_joborder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborderproduct',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='joborderproduct',
            name='packed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joborderproduct',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
