# Generated by Django 4.2.28 on 2026-03-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_joborderproduct_datetime_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboroutput',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='laboroutput',
            name='output_type',
            field=models.CharField(choices=[('DTF press', 'DTF press'), ('Cut/Coat', 'Cut/Coat'), ('Assemble', 'Assemble'), ('Box', 'Box'), ('Envelope', 'Envelope'), ('Subli Press', 'Subli Press'), ('Stick Press', 'Stick Press'), ('Engrave', 'Engrave'), ('UV', 'UV'), ('Vinyl Press', 'Vinyl Press'), ('PBOperator', 'PBOperator'), ('PBTranspo', 'PBTranspo'), ('Book Bound', 'Book Bound')], max_length=100),
        ),
    ]
