# Generated by Django 4.2.28 on 2026-03-17 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_laboroutput_status_alter_laboroutput_output_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalslipitem',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='withdrawalslipitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ws_items', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='withdrawalslipitem',
            name='quantity_approved',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='withdrawalslipitem',
            name='released_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalslipitem',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
