# Generated by Django 4.2.28 on 2026-03-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_withdrawalslipitem_datetime_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalslipitem',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
