# Generated by Django 4.2.28 on 2026-03-17 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_withdrawalslipitem_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborderproductmaterial',
            name='quantity_released',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='withdrawalslipitem',
            name='jop_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ws_items', to='inventory.joborderproductmaterial'),
        ),
    ]
