# Generated by Django 4.2.28 on 2026-03-19 06:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_joborderproductmaterial_quantity_released_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0.0)),
                ('unit', models.CharField(blank=True, default='pc', max_length=50)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.deliveryreceipt')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dr_items', to='inventory.inventoryitem')),
            ],
        ),
    ]
