# Generated by Django 4.2.28 on 2026-03-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_deliveryreceiptitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='absences',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='benefits',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='cash_advance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='incident_report',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='tardiness',
            field=models.FloatField(default=0.0),
        ),
    ]
